[package]
name = "kdb_c_api"
version = "0.1.0"
authors = ["diamondrod"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/diamondrod/rust_kdb_c_api"
description = """
Wrapper of kdb+ C API.
"""

[dependencies]

[dev-dependencies]
libc="^0.2"